// <auto-generated />
using Menu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Menu.Migrations
{
    [DbContext(typeof(MenuContext))]
    [Migration("20251111160059_new data")]
    partial class newdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Menu.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://assets.tmecosys.com/image/upload/t_web_rdp_recipe_584x480_1_5x/img/recipe/ras/Assets/d1b38708de15e20816113dc7c447ab99/Derivates/563c08eba9aa94895a39fb0249fecda402d92e28.jpg",
                            Name = "Spaghetti Bolognese",
                            Price = 12.99
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://cdn.loveandlemons.com/wp-content/uploads/2024/12/caesar-salad.jpg",
                            Name = "Caesar Salad",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://www.olivemagazine.com/media/lx4f6n1y/margherita-pizza-1-af-web.jpg",
                            Name = "Margherita Pizza",
                            Price = 14.99
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1645112411341-6c4ee32510b8?w=600",
                            Name = "Chicken Alfredo",
                            Price = 15.99
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1562547256-4-4a48e0c01d0?w=600",
                            Name = "Pad Thai",
                            Price = 11.99
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=600",
                            Name = "Sushi Platter",
                            Price = 18.989999999999998
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600",
                            Name = "Greek Salad",
                            Price = 10.99
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600",
                            Name = "Beef Tacos",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
                            Name = "Grilled Salmon",
                            Price = 19.989999999999998
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://images.unsplash.com/photo-1455619452474-d2be8b1e4e31?w=600",
                            Name = "Vegetable Curry",
                            Price = 12.99
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://images.unsplash.com/photo-1599599810694-a5f1f4d67c6a?w=600",
                            Name = "Lasagna",
                            Price = 13.99
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600",
                            Name = "Chocolate Cake",
                            Price = 7.9900000000000002
                        });
                });

            modelBuilder.Entity("Menu.Models.DishIngredient", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DishIngredients");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 38
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 4
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 5
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 6
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 38
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 7
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 37
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 10
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 11
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 38
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 12
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 13
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 14
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 39
                        },
                        new
                        {
                            DishId = 6,
                            IngredientId = 15
                        },
                        new
                        {
                            DishId = 6,
                            IngredientId = 16
                        },
                        new
                        {
                            DishId = 6,
                            IngredientId = 17
                        },
                        new
                        {
                            DishId = 6,
                            IngredientId = 18
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 4
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 19
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 20
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 21
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 22
                        },
                        new
                        {
                            DishId = 8,
                            IngredientId = 23
                        },
                        new
                        {
                            DishId = 8,
                            IngredientId = 24
                        },
                        new
                        {
                            DishId = 8,
                            IngredientId = 25
                        },
                        new
                        {
                            DishId = 8,
                            IngredientId = 26
                        },
                        new
                        {
                            DishId = 9,
                            IngredientId = 16
                        },
                        new
                        {
                            DishId = 9,
                            IngredientId = 27
                        },
                        new
                        {
                            DishId = 9,
                            IngredientId = 28
                        },
                        new
                        {
                            DishId = 9,
                            IngredientId = 37
                        },
                        new
                        {
                            DishId = 10,
                            IngredientId = 30
                        },
                        new
                        {
                            DishId = 10,
                            IngredientId = 31
                        },
                        new
                        {
                            DishId = 10,
                            IngredientId = 32
                        },
                        new
                        {
                            DishId = 10,
                            IngredientId = 22
                        },
                        new
                        {
                            DishId = 11,
                            IngredientId = 34
                        },
                        new
                        {
                            DishId = 11,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 11,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 11,
                            IngredientId = 38
                        },
                        new
                        {
                            DishId = 12,
                            IngredientId = 33
                        },
                        new
                        {
                            DishId = 12,
                            IngredientId = 34
                        },
                        new
                        {
                            DishId = 12,
                            IngredientId = 35
                        },
                        new
                        {
                            DishId = 12,
                            IngredientId = 36
                        });
                });

            modelBuilder.Entity("Menu.Models.Ingredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spaghetti"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ground Beef"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tomato Sauce"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romaine Lettuce"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Caesar Dressing"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Croutons"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pizza Dough"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fresh Mozzarella"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fresh Basil"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Alfredo Sauce"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Rice Noodles"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Fish Sauce"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Peanuts"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sushi Rice"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Salmon"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Nori"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Avocado"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Feta Cheese"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Olives"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Tomatoes"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Tortillas"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Beef"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Cheddar Cheese"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Sour Cream"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Lemon Juice"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Butter"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Coconut Milk"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Curry Powder"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Spinach"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Flour"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Olive Oil"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Parmesan Cheese"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Bell Pepper"
                        });
                });

            modelBuilder.Entity("Menu.Models.DishIngredient", b =>
                {
                    b.HasOne("Menu.Models.Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menu.Models.Ingredients", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Menu.Models.Dish", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("Menu.Models.Ingredients", b =>
                {
                    b.Navigation("DishIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
